# Generated by Django 4.2.3 on 2023-08-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pername', models.CharField(max_length=250)),
                ('perimg', models.ImageField(upload_to='pic')),
                ('perdesc', models.TextField()),
            ],
        ),
    ]
